### ISSUE TITLE
mobile issue

### ISSUE THREAD

**Issue by alexandresoaresramos** [dsasmita/magento2-whatsapp-chat#3]
After configure at admin, mobile version not acept new configuration

https://prnt.sc/z3j7ob
its not possible search this number 085236725506 because country code is wrong

my correct config is +551199999999 (example)

if want test see here www.vipracing.com.br

**Comment by dsasmita** [comment]
@alexandresoaresramos yes, that number only exists in Indonesia country, you can change the number
